on:
  rss:
    url:
      # Art - Anime
      - https://sukebei.nyaa.si/?page=rss&c=1_1&f=0
      # Art - Doujinshi
      - https://sukebei.nyaa.si/?page=rss&c=1_2&f=0
      # Art - Games
      - https://sukebei.nyaa.si/?page=rss&c=1_3&f=0
      # Art - Manga
      - https://sukebei.nyaa.si/?page=rss&c=1_4&f=0
      # Art - Pictures
      - https://sukebei.nyaa.si/?page=rss&c=1_5&f=0
      # Real life - Photobooks and Pictures
      - https://sukebei.nyaa.si/?page=rss&c=2_1&f=0
      # Real life - Videos
      - https://sukebei.nyaa.si/?page=rss&c=2_2&f=0
    parserConfig:
      customFields: {
        item: [
          ['nyaa:seeders', 'seeders'],
          ['nyaa:leechers', 'leechers'],
          ['nyaa:downloads', 'downloads'],
          ['nyaa:infoHash', 'infoHash'],
          ['nyaa:size', 'size'],
          ['nyaa:categoryId', 'categoryId'],
        ]
      }
    config:
      skipOnError: true

jobs:
  post:
    name: Post rss updates to the discord
    runs-on: ubuntu-latest
    steps:
      - name: Post
        run: |
          {
            name=$(awk -F '/' '{print $NF}' <<<${{ on.rss.outputs.link }})
            curl -s ${{ on.rss.outputs.link }} -o ${name} && \
            link=$(curl -s $(curl -s -F "file=@${name}" https://api.anonfiles.com/upload|awk 'BEGIN{FS=","}/full/{sub(/^.*https/,"https",$2);sub(/"$/,"",$2);print $2}')|awk '/https:\/\/cdn/{print}'|awk 'END{sub(/^.*https/,"https",$0);sub(/".*$/,"",$0);print}') && \
            if [[ ${{ on.rss.outputs.categoryId }} == "1_1" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_ANIME }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "1_2" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_DOUJINSHI }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "1_3" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_GAMES }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "1_4" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_MANGA }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "1_5" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_PICTURES }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "2_1" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_PHOTOBOOKS_AND_PICTURES }}
            elif [[ ${{ on.rss.outputs.categoryId }} == "2_2" ]]; then
              curl -s \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                -d '{"embeds":[{"title":"**${{ on.rss.outputs.title }}**","description":"${{ on.rss.outputs.contentSnippet }}","url":"${{ on.rss.outputs.guid }}", "thumbnail":{"url":"https://sukebei.nyaa.si/static/img/avatar/default.png"}, "fields": [{"name":":seedling: seeders","value":"${{ on.rss.outputs.seeders }}","inline": true},{"name":":arrow_down_small: leechers","value":"${{ on.rss.outputs.leechers }}","inline": true},{"name":":arrow_double_down: downloads","value":"${{ on.rss.outputs.downloads }}","inline": true},{"name":":open_file_folder: size","value":"${{ on.rss.outputs.size }}","inline": true},{"name":":hash: hash","value":"${{ on.rss.outputs.infoHash }}","inline": true},{"name":":link: link","value":"'"${link}"'"}]}]}' \
                ${{ secrets.DISCORD_NYAA_SUKEBEI_VIDEOS }}
            fi
          } || exit 0
